from api.db import furniture_collection
from pydantic import BaseModel
from fastapi import HTTPException, UploadFile, status
from datetime import datetime
from typing import Optional,List,Dict
from pymongo import DESCENDING , ASCENDING
from bson import ObjectId
from api.models.FileUpload import FileUpload
from api.db import users_collection
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from api.models.FileUpload import FileUpload
import os
from dotenv import load_dotenv

load_dotenv () 

class Furniture(BaseModel):
    title: str
    description: str
    category: str
    brand : Optional[str] = None
    price: Optional[int] = None
    is_for_rent: Optional[bool] = False
    rent_price: Optional[int] = None
    is_for_sale: Optional[bool] = False
    condition: str
    availability_status: str
    dimensions: Optional[str] = None
    location: str
    image: Optional[str] = None # default profile picture url and single images 
    images: Optional[List[str]] = [] #multiple images and default empty list
    created_by: str
    created_at: str  
    status: Optional[str] = None  

# Furniture model class 
    @staticmethod 
    def add_furniture(furniture_data: dict, files: List[UploadFile]):
        """ Adds a new furniture to the collection. """
        try:
            file_upload = FileUpload()  # Initialize FileUpload class

            # Process and save files
            images = []
            for file in files:

                file_upload = FileUpload()  # Initialize FileUpload class

                file_url = file_upload.upload_image(file)
                
                images.append(file_url)

            images = [img for img in images if img]
             # Store images based on the number of files
             
            if len(images) == 1:
                furniture_data["image"] = images[0]
                furniture_data["images"] = []
            else:
                furniture_data["image"] = None
                furniture_data["images"] = images

            # Ensure _id is auto-generated by MongoDB (don't manually assign it)
            result = furniture_collection.insert_one(furniture_data)
            return True if result.inserted_id else False
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=str(e)
            )
        
    @staticmethod
    def get_furniture(user_id: str, query_param: dict):
        try:
            search = query_param.get("search", "")
            sort_by = query_param.get("sort_by", "created_at")
            order = query_param.get("sort_order", "desc").lower()
            page = int(query_param.get("page", 1))
            limit = int(query_param.get("limit", 10))
            listing_type = query_param.get("listing_type", "all")

            # -------------------------
            # BASE QUERY
            # -------------------------
            query = {
                "created_by": user_id,
                "status": "approved"
            }

            # -------------------------
            # LISTING TYPE FILTER
            # -------------------------
            if listing_type == "buy":
                query["is_for_sale"] = True

            elif listing_type == "rent":
                query["is_for_rent"] = True

            else:
                query["$or"] = [
                    {"is_for_sale": True},
                    {"is_for_rent": True}
                ]

            # -------------------------
            # SEARCH FILTER (FIXED)
            # -------------------------
            if search:
                    query["$or"] = [
                        {"title": {"$regex": search, "$options": "i"}},
                        {"description": {"$regex": search, "$options": "i"}},
                        {"category": {"$regex": search, "$options": "i"}}
                    ]
                

            # -------------------------
            # SORT VALIDATION
            # -------------------------
            allowed_sort_fields = ["price", "rent_price", "created_at", "title", "category"]

            if sort_by not in allowed_sort_fields:
                sort_by = "created_at"

            sort_order = 1 if order == "asc" else -1

            skip = (page - 1) * limit

            # -------------------------
            # TOTAL COUNT
            # -------------------------
            total_count = furniture_collection.count_documents(query)

            # -------------------------
            # FETCH DATA
            # -------------------------
            cursor = (
                furniture_collection
                .find(query)
                .collation({"locale": "en", "strength": 2})  # case-insensitive sort
                .sort(sort_by, sort_order)
                .skip(skip)
                .limit(limit)
            )

            furniture_list = list(cursor)

            # -------------------------
            # FORMAT DATA
            # -------------------------
            def safe_float(value):
                if isinstance(value, (int, float)):
                    return float(value)
                if isinstance(value, str) and value.strip():
                    try:
                        return float(value)
                    except:
                        return 0.0
                return 0.0

            for furniture in furniture_list:
                furniture["_id"] = str(furniture["_id"])

                # datetime fix
                if isinstance(furniture.get("created_at"), datetime):
                    furniture["created_at"] = furniture["created_at"].isoformat()

                if isinstance(furniture.get("updated_at"), datetime):
                    furniture["updated_at"] = furniture["updated_at"].isoformat()

                # numeric fix
                furniture["price"] = safe_float(furniture.get("price"))
                furniture["rent_price"] = safe_float(furniture.get("rent_price"))

                # boolean fix
                furniture["is_for_sale"] = bool(furniture.get("is_for_sale", False))
                furniture["is_for_rent"] = bool(furniture.get("is_for_rent", False))

            # -------------------------
            # RESPONSE
            # -------------------------
            return {
                "data": furniture_list,
                "pagination": {
                    "total": total_count,
                    "page": page,
                    "limit": limit,
                    "total_pages": (total_count + limit - 1) // limit
                }
            }

        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
                      
    @staticmethod
    def update_furniture(
        furniture_id: str,
        update_data: dict,
        files: Optional[List[UploadFile]] = None,
        replace_indexes: Optional[List[int]] = None
    ) -> bool:
        try:
            # -------------------------
            # FETCH CURRENT DATA
            # -------------------------
            current = furniture_collection.find_one({
                "_id": ObjectId(furniture_id)
            })

            if not current:
                return False

            # -------------------------
            # PREPARE EXISTING IMAGES
            # -------------------------
            existing_images = current.get("images", []).copy()

            if not existing_images and current.get("image"):
                existing_images = [current["image"]]

            images_updated = False

            # -------------------------
            # IMAGE HANDLING (STRICT)
            # -------------------------
            if files:
                new_image_urls = []

                for file in files:
                    file_url = FileUpload().upload_image(file)
                    # file_url = f"https://furnspace.onrender.com/static/uploads/{unique_filename}"
                    new_image_urls.append(file_url)

                #  STRICT REPLACE MODE
                if replace_indexes is not None:

                    if not isinstance(replace_indexes, list):
                        raise HTTPException(status_code=400, detail="replace_indexes must be a list")

                    # 🔒 enforce EXACT match
                    if len(replace_indexes) != len(new_image_urls):
                        raise HTTPException(
                            status_code=400,
                            detail="replace_indexes and files count must match"
                        )

                    for i, index in enumerate(replace_indexes):

                        if not isinstance(index, int) or index < 0:
                            raise HTTPException(
                                status_code=400,
                                detail=f"Invalid index: {index}"
                            )

                        if index >= len(existing_images):
                            raise HTTPException(
                                status_code=400,
                                detail=f"Index out of range: {index}"
                            )

                        # REPLACE ONLY
                        existing_images[index] = new_image_urls[i] or existing_images[index]

                    images_updated = True

                # STRICT ADD MODE
                else:
                    existing_images.extend(new_image_urls)
                    images_updated = True
            # -------------------------
            # PREPARE FINAL UPDATE DATA
            # -------------------------
            final_update = {}

            allowed_fields = [
                "title",
                "description",
                "price",
                "category",
                "rent_price",
                "availability_status",
                "condition",
                "dimensions",
                "location",
                "is_for_sale",
                "is_for_rent",
                "brand"
            ]

            for key in allowed_fields:
                if key in update_data:
                    final_update[key] = update_data[key]

            # Only update images if changed
            if images_updated:

                # Remove empty / None values
                existing_images = [img for img in existing_images if img]

                if len(existing_images) == 0:
                    final_update["image"] = None
                    final_update["images"] = []

                elif len(existing_images) == 1:
                    # SINGLE IMAGE → store in `image`
                    final_update["image"] = existing_images[0]
                    final_update["images"] = []

                else:
                    # MULTIPLE IMAGES → store in `images`
                    final_update["image"] = None
                    final_update["images"] = existing_images

            # Timestamp
            final_update["updated_at"] = datetime.utcnow()

            if not final_update:
                raise HTTPException(
                    status_code=400,
                    detail="No valid fields or images provided for update"
                )

            # -------------------------
            # DATABASE UPDATE
            # -------------------------
            result = furniture_collection.update_one(
                {"_id": ObjectId(furniture_id)},
                {"$set": final_update}
            )

            return result.modified_count > 0

        except HTTPException:
            raise

        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
            
    @staticmethod
    def search_furniture_by_category_or_title(category: Optional[str] = None, title: Optional[str] = None) -> List[Dict]:
        """ Searches for furniture items by category or title, ignoring case. """
        try:
            query = {}
            if category and title:
                query = {"$or": [{"category": {"$regex": category, "$options": "i"}}, {"title": {"$regex": title, "$options": "i"}}]}
            elif category:
                query = {"category": {"$regex": category, "$options": "i"}}
            elif title:
                query = {"title": {"$regex": title, "$options": "i"}}
            
            furniture_list = list(furniture_collection.find(query))
            for furniture in furniture_list:
                furniture['_id'] = str(furniture['_id'])  # Convert ObjectId to string
                if isinstance(furniture['created_at'], datetime):
                    furniture['created_at'] = furniture['created_at'].isoformat()  # Convert datetime to string
            return furniture_list
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=str(e)
            )
    
    @staticmethod
    def delete_furniture(furniture_id: str) -> dict:
        """ Deletes a furniture item based on furniture_id. """
        try:
            result = furniture_collection.delete_one({"_id": ObjectId(furniture_id)})
            if result.deleted_count > 0:
                return {"message": "Furniture item deleted successfully","furniture_id": furniture_id}
            else:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail=f"No furniture found with id: {furniture_id}"
                )
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"An error occurred while deleting the furniture item: {str(e)}"
            )
 
    @staticmethod
    def get_all_furniture(query_params: dict):
        try:
            search = query_params.get("search", "")
            sort_by = query_params.get("sort_by", "created_at")
            order = query_params.get("order", "desc").lower()
            page = int(query_params.get("page", 1))
            limit = int(query_params.get("limit", 10))
            listing_type = query_params.get("listing_type", "all")

            query = {"status": "approved"}

            # FILTER
            if listing_type == "buy":
                query["is_for_sale"] = True

            elif listing_type == "rent":
                query["is_for_rent"] = True

            else:
                query["$or"] = [
                    {"is_for_sale": True},
                    {"is_for_rent": True}
            ]

            # SEARCH
            if search:
                query["$or"] = [
                    {"title": {"$regex": search, "$options": "i"}},
                    {"description": {"$regex": search, "$options": "i"}},
                    {"category": {"$regex": search, "$options": "i"}}
                ]

            # SORT VALIDATION
            allowed_sort_fields = ["price", "rent_price", "created_at", "title", "category"]

            if sort_by not in allowed_sort_fields:
                sort_by = "created_at"

            sort_order = 1 if order == "asc" else -1
            skip = (page - 1) * limit

            total_count = furniture_collection.count_documents(query)

            furniture_list = list(
                furniture_collection
                .find(query)
                .collation({"locale": "en", "strength": 2})
                .sort(sort_by, sort_order)
                .skip(skip)
                .limit(limit)
            )

            # FORMAT DATA
            for furniture in furniture_list:
                furniture["_id"] = str(furniture["_id"])

                if isinstance(furniture.get("updated_at"), datetime):
                    furniture["updated_at"] = furniture["updated_at"].isoformat()
                
                if isinstance(furniture.get("created_at"), datetime):
                    furniture["created_at"] = furniture["created_at"].isoformat()

                # SAFE NORMALIZATION
                def safe_float(value):
                    if isinstance(value, (int, float)):
                        return float(value)
                    if isinstance(value, str) and value.strip() != "":
                        try:
                            return float(value)
                        except ValueError:
                            return 0.0
                    return 0.0

                furniture["price"] = safe_float(furniture.get("price"))
                furniture["rent_price"] = safe_float(furniture.get("rent_price"))

                # CRITICAL FIX
                furniture["is_for_sale"] = bool(furniture.get("is_for_sale", False))
                furniture["is_for_rent"] = bool(furniture.get("is_for_rent", False))

            return {
                "items": furniture_list,
                "pagination": {
                    "total": total_count,
                    "page": page,
                    "limit": limit,
                    "total_pages": (total_count + limit - 1) // limit
                }
            }

        except Exception as e:
            raise HTTPException(
                status_code=500,
                detail=f"Error fetching furniture: {str(e)}"
            )

    @staticmethod
    def send_email(data: dict):
        try:
            # Retrieve user email from the user_collection
            user = users_collection.find_one({"_id": ObjectId(data["user_id"])})
            if not user or "email" not in user:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail="User not found or email not available"
                )
            email = user["email"]  # Extract email from the user document

            sender_email = os.getenv("MAIL_USERNAME1")
            sender_password = os.getenv("MAIL_PASSWORD1")
            smtp_server = os.getenv("MAIL_SERVER")
            smtp_port = os.getenv("MAIL_PORT")

            subject = "Furniture Approval Notification"
            if data["status"] == "approved":
                body = f"Dear User,\n\nYour furniture has been approved.\n\nRegards,\nAdmin Team"
            else:
                body = f"Dear User,\n\nYour furniture has been rejected.\n\nRegards,\nAdmin Team"
            msg = MIMEMultipart()
            msg["From"] = sender_email
            msg["To"] = email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.sendmail(sender_email, email, msg.as_string())

        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to send email: {str(e)}"
            )

    @staticmethod
    def update_furniture_status(user_id: str, furniture_id: str, status_data: dict) -> dict:
        """ Updates the status of a specific furniture item for a user. """
        try:
            # Extract new status from input data
            new_status = status_data.get("status")
            if not new_status:
                raise HTTPException(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    detail="Status is required to update furniture status"
                )
            
            # Retrieve user email from the user_collection
            user = users_collection.find_one({"_id": ObjectId(user_id)})
            if not user or "email" not in user:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail="User not found or email not available"
                )
            email = user["email"]  # Extract email from the user document
            
            # Find the specific furniture item for the user
            furniture_item = furniture_collection.find_one({"_id": ObjectId(furniture_id), "created_by": user_id})
            if not furniture_item:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail=f"No furniture item found with ID: {furniture_id} for user: {user_id}"
                )
            
            # Update the status for the specific furniture item
            result = furniture_collection.update_one(
                {"_id": ObjectId(furniture_id), "created_by": user_id},
                {"$set": {"status": new_status}}
            )
            
            # Send email notification if the status was updated
            if result.modified_count > 0:
                Furniture.send_email({
                    "user_id": user_id,
                    "email": email,
                    "status": new_status
                })
            
            # Prepare response data
            response_data = {
                "message": f"Furniture status updated successfully for furniture ID: {furniture_id}",
                "modified_count": result.modified_count
            }
            return response_data

        except Exception as e:
            print(f"Error updating furniture status: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"An error occurred: {str(e)}"
            )            

    @staticmethod
    def get_furniture_by_id(furniture_id: str) -> dict:
        """ Retrieves a specific furniture item by its ID. """
        try:
            print(f"Fetching furniture with ID: {furniture_id}")  # Debug log
            furniture_item = furniture_collection.find_one({"_id": ObjectId(furniture_id)})
            if not furniture_item:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail=f"No furniture found with ID: {furniture_id}"
                )
            furniture_item['_id'] = str(furniture_item['_id'])  # Convert ObjectId to string
            if isinstance(furniture_item['created_at'], datetime):
                furniture_item['created_at'] = furniture_item['created_at'].isoformat()  # Convert datetime to string
            return furniture_item
        except Exception as e:
            print(f"Error in get_furniture_by_id: {str(e)}")  # Debug log
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=str(e)
            )

    @staticmethod
    def list_all_furniture() -> List[Dict]:
        """ Retrieves all furniture items from the collection without any filtering. """
        try:
            furniture_list = list(furniture_collection.find())
            for furniture in furniture_list:
                furniture['_id'] = str(furniture['_id'])  # Convert ObjectId to string
                if isinstance(furniture['created_at'], datetime):
                    furniture['created_at'] = furniture['created_at'].isoformat()  # Convert datetime to string
                
                # Ensure price is properly formatted as integer where applicable
                if 'price' in furniture and furniture['price'] is not None:
                    try:
                        furniture['price'] = int(furniture['price'])
                    except (ValueError, TypeError):
                        pass
                        
            return furniture_list
        except Exception as e:
            print(f"Error in list_all_furniture: {str(e)}")  # Debug log
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=str(e)
            )